# Example configuration file for kodi-plex sync. example.config.yml will be
# ignored. To use, copy this file as a new config.yml file and configure to your
# liking!
servers:
  source:
    type: kodi
    hostname: localhost
    port: 9090
  dest:
    type: plex
    hostname: 192.168.1.123
    username: test@example.com
    password: pass_goes_here
    # If using a manged user, uncomment and enter managed UN (and optional PW).
    #managed_username: ~
    #managed_pin: ~
